all: tags .copy

include Makefile

# https://github.com/alex-courtis/arch/blob/7ca6c8d7f7aa910ec522470bb7a96ddb24c9a1ea/bin/ctags-something
tags: $(SRC_C) $(SRC_CXX) $(INC_H) $(PRO_H)
	ctags-c   $(CFLAGS)   $(CPPFLAGS) --project-src $(SRC_C)   $(INC_H) $(PRO_H)
	ctags-c++ $(CXXFLAGS) $(CPPFLAGS) --project-src $(SRC_CXX) $(INC_H) $(PRO_H) --append

.copy: way-displays cfg.yaml
	scp cfg.yaml gigantor:.config/way-displays/cfg.yaml
	scp way-displays gigantor:bin
	touch .copy

