name: CI
on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master
  workflow_dispatch: {}
  schedule:
    - cron: '0 0 * * 0' # weekly on sundays

jobs:
  all:
    runs-on: ubuntu-latest

    container:
      image: archlinux:multilib-devel

    defaults:
      run:
        shell: sh -ec "runuser runner {0}" # assume the runner user except where overridden by root

    env:
      DEBUGINFOD_URLS: "https://debuginfod.archlinux.org" # profile thus debuginfod.sh is not executed
      DEBUGINFOD_CACHE_PATH: "/tmp/debuginfod_client"

    steps:
      - uses: actions/checkout@v7

      - name: create user
        shell: sh -e {0}
        # magic numbers and names not available in environment
        run: |
          groupadd --gid 118 docker
          useradd -m -s /bin/sh --uid 1001 --gid docker runner

      - name: set source permissions
        run: chown -R runner:docker .
        shell: sh -e {0}

      - name: install arch packages
        shell: sh -e {0}
        run: bld/docker-install-arch.sh

      - run: make          clean
      - run: make CC=gcc   all
      - run: make CC=gcc   test
      - run: make CC=gcc   test-vg

      - run: make clean cppcheck

      - run: make          clean
      - run: make CC=clang all
      - run: make CC=clang test
      - run: make CC=clang test-vg

      - name: build and install 32-bit libyaml
        run: bld/docker-install-libyaml-32.sh
        shell: sh -e {0}

      - run: make                      clean
      - run: make CC=gcc   MFLAGS=-m32 test
      - run: make CC=gcc   MFLAGS=-m32 test-vg

      # Temporarily remove 32 bit clang tests:
      # /usr/bin/ld: cannot find -lgcc_s: No such file or directory
      # /usr/lib32/libgcc_s_asneeded.so and libgcc_s.so are missing from 16.1.1+r346+g4e03491b401d-1
      # They are present at 16.1.1+r12+g301eb08fa2c5-1
      # - run: make                      clean
      # - run: make CC=clang MFLAGS=-m32 test
      # - run: make CC=clang MFLAGS=-m32 test-vg

      - name: build and install include-what-you-use
        run: bld/docker-install-iwyu.sh
        shell: sh -e {0}

      - run: make clean iwyu

